spring:
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost
server:
  port: 9092
mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package:
    - ru.otus.changelog
